using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using BoxingSite.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using System;

namespace BoxingSite.DAL
{
    public class ApplicationDbInitializer : DropCreateDatabaseIfModelChanges<ApplicationDbContext>
    {
        protected override void Seed(ApplicationDbContext context)
        {
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
            var userStore = new UserStore<ApplicationUser>(context);

            //_____________________________________________________________________
            //populating the Role table - Administrator
            if (!roleManager.RoleExists(RoleNames.ROLE_ADMINISTRATOR))
            {
                var roleresult = roleManager.Create(new IdentityRole(RoleNames.ROLE_ADMINISTRATOR));
            }
            if (!roleManager.RoleExists(RoleNames.ROLE_STAFF))
            {
                var roleresult = roleManager.Create(new IdentityRole(RoleNames.ROLE_STAFF));
            }
          
            if (!roleManager.RoleExists(RoleNames.ROLE_SUSPENDED))
            {
                var roleresult = roleManager.Create(new IdentityRole(RoleNames.ROLE_SUSPENDED));
            }




            // ________________________________________________________________
            // Seeding Promotions and Tickets

            // All Tickets will link to a single Promotion - although multiple tickets can link to the same promotion. 
            // Promotions. 
            var promotions = new List<Promotion>()
            {
                new Promotion {
                    // id - autogenerated 
                    Name ="Soultown Festival 2020 -Saturday 5th September",
                    PromotedBy = "King Boxing",
                    PromotionDate = new DateTime(2020, 4, 1),
                    PromotionStartTime = new TimeSpan(19, 30, 0),
                    PromotionEndTime = new TimeSpan(20, 30, 0),

                    LocationBuiding = "The Big Ole Pizaa Joint",
                    LocationStreetAddress = "22 Hap'nin street",
                    LocationPostCode = "G3245D",
                    LocationCity = "Glasgow",
                    AboutEvent = "Andre Ward did it all in his boxing career: Olympic Gold as an amateur and undefeated World Champion as a professional." +
                                 "Andre started boxing at the age of 9 and went on to win 115 of 120 amateur contests - culminating in an Olympic Gold in Athens in 2004." +
                                 "As a professional Andre won World Titles at both Super-Middleweight and Light-Heavyweight. He retired with an unbeaten 32-0 record in 2017 as one of the best pound-for-pound fighters on the planet." +
                                 "Event guests will gain insight into Andre's career - in which he was trained throughout by his godfather Virgil Hunter - and hear about what it takes to get to the top of the boxing world.",
                    Photo = "Glasgow",
                    TotalSeats = 88,
                    AmountGoing = 22,
                    RemainingSeats = 66

                },
                new Promotion {
                    // id - autogenerated 
                    Name ="An Evening With Andre Ward",
                    PromotedBy = "King Boxing",
                    PromotionDate = new DateTime(2020, 7, 2),
                    PromotionStartTime = new TimeSpan(19, 30, 0),
                    PromotionEndTime = new TimeSpan(20, 30, 0),

                    LocationBuiding = "The Big Ole Pizaa Joint",
                    LocationStreetAddress = "22 Hap'nin street",
                    LocationPostCode = "G3245D",
                    LocationCity = "Glasgow",
                    AboutEvent = "Andre Ward did it all in his boxing career: Olympic Gold as an amateur and undefeated World Champion as a professional." +
                                 "Andre started boxing at the age of 9 and went on to win 115 of 120 amateur contests - culminating in an Olympic Gold in Athens in 2004." +
                                 "As a professional Andre won World Titles at both Super-Middleweight and Light-Heavyweight. He retired with an unbeaten 32-0 record in 2017 as one of the best pound-for-pound fighters on the planet." +
                                 "Event guests will gain insight into Andre's career - in which he was trained throughout by his godfather Virgil Hunter - and hear about what it takes to get to the top of the boxing world.",
                    Photo = "Glasgow",
                    TotalSeats = 88,
                    AmountGoing = 22,
                    RemainingSeats = 66
                },
                new Promotion {
                    // id - autogenerated 
                    Name ="Steve Thomson the Great",
                    PromotedBy = "King Boxing",
                    PromotionDate = new DateTime(2020, 4, 1),
                    PromotionStartTime = new TimeSpan(19, 30, 0),
                    PromotionEndTime = new TimeSpan(20, 30, 0),

                    LocationBuiding = "The Big Ole Pizaa Joint",
                    LocationStreetAddress = "22 Hap'nin street",
                    LocationPostCode = "G3245D",
                    LocationCity = "Glasgow",
                    AboutEvent = "Andre Ward did it all in his boxing career: Olympic Gold as an amateur and undefeated World Champion as a professional." +
                                 "Andre started boxing at the age of 9 and went on to win 115 of 120 amateur contests - culminating in an Olympic Gold in Athens in 2004." +
                                 "As a professional Andre won World Titles at both Super-Middleweight and Light-Heavyweight. He retired with an unbeaten 32-0 record in 2017 as one of the best pound-for-pound fighters on the planet." +
                                 "Event guests will gain insight into Andre's career - in which he was trained throughout by his godfather Virgil Hunter - and hear about what it takes to get to the top of the boxing world.",
                    Photo = "Glasgow",
                    TotalSeats = 88,
                    AmountGoing = 22,
                    RemainingSeats = 66

                },
                new Promotion {
                    // id - autogenerated 
                    Name ="One in a Million",
                    PromotedBy = "King Boxing",
                    PromotionDate = new DateTime(2020, 7, 2),
                    PromotionStartTime = new TimeSpan(19, 30, 0),
                    PromotionEndTime = new TimeSpan(20, 30, 0),

                    LocationBuiding = "The Big Ole Pizaa Joint",
                    LocationStreetAddress = "22 Hap'nin street",
                    LocationPostCode = "G3245D",
                    LocationCity = "Glasgow",
                    AboutEvent = "Andre Ward did it all in his boxing career: Olympic Gold as an amateur and undefeated World Champion as a professional." +
                                 "Andre started boxing at the age of 9 and went on to win 115 of 120 amateur contests - culminating in an Olympic Gold in Athens in 2004." +
                                 "As a professional Andre won World Titles at both Super-Middleweight and Light-Heavyweight. He retired with an unbeaten 32-0 record in 2017 as one of the best pound-for-pound fighters on the planet." +
                                 "Event guests will gain insight into Andre's career - in which he was trained throughout by his godfather Virgil Hunter - and hear about what it takes to get to the top of the boxing world.",
                    Photo = "Glasgow",
                    TotalSeats = 88,
                    AmountGoing = 22,
                    RemainingSeats = 66
                },
                new Promotion {
                    // id - autogenerated 
                    Name ="Unspoken Greats",
                    PromotedBy = "King Boxing",
                    PromotionDate = new DateTime(2020, 8, 8),
                    PromotionStartTime = new TimeSpan(19, 30, 0),
                    PromotionEndTime = new TimeSpan(21, 30, 0),

                    LocationBuiding = "The Plazza",
                    LocationStreetAddress = "22 Hap'nin street",
                    LocationPostCode = "G3245D",
                    LocationCity = "Glasgow",
                    AboutEvent = "Andre Ward did it all in his boxing career: Olympic Gold as an amateur and undefeated World Champion as a professional." +
                                 "Andre started boxing at the age of 9 and went on to win 115 of 120 amateur contests - culminating in an Olympic Gold in Athens in 2004." +
                                 "As a professional Andre won World Titles at both Super-Middleweight and Light-Heavyweight. He retired with an unbeaten 32-0 record in 2017 as one of the best pound-for-pound fighters on the planet." +
                                 "Event guests will gain insight into Andre's career - in which he was trained throughout by his godfather Virgil Hunter - and hear about what it takes to get to the top of the boxing world.",
                    Photo = "Glasgow",
                    TotalSeats = 88,
                    AmountGoing = 22,
                    RemainingSeats = 66

                },
                new Promotion {
                    // id - autogenerated 
                    Name ="The Happening is Happening",
                    PromotedBy = "King Boxing",
                    PromotionDate = new DateTime(2020, 7, 2),
                    PromotionStartTime = new TimeSpan(19, 30, 0),
                    PromotionEndTime = new TimeSpan(20, 30, 0),

                    LocationBuiding = "The Big Ole Pizaa Joint",
                    LocationStreetAddress = "22 Hap'nin street",
                    LocationPostCode = "G3245D",
                    LocationCity = "Glasgow",
                    AboutEvent = "Andre Ward did it all in his boxing career: Olympic Gold as an amateur and undefeated World Champion as a professional." +
                                 "Andre started boxing at the age of 9 and went on to win 115 of 120 amateur contests - culminating in an Olympic Gold in Athens in 2004." +
                                 "As a professional Andre won World Titles at both Super-Middleweight and Light-Heavyweight. He retired with an unbeaten 32-0 record in 2017 as one of the best pound-for-pound fighters on the planet." +
                                 "Event guests will gain insight into Andre's career - in which he was trained throughout by his godfather Virgil Hunter - and hear about what it takes to get to the top of the boxing world.",
                    Photo = "Glasgow",
                    TotalSeats = 88,
                    AmountGoing = 22,
                    RemainingSeats = 66
                },
                new Promotion {
                    // id - autogenerated 
                    Name ="Free Falling - the Bananza",
                    PromotedBy = "King Boxing",
                    PromotionDate = new DateTime(2020, 4, 1),
                    PromotionStartTime = new TimeSpan(19, 30, 0),
                    PromotionEndTime = new TimeSpan(20, 30, 0),

                    LocationBuiding = "The Big Ole Pizaa Joint",
                    LocationStreetAddress = "22 Hap'nin street",
                    LocationPostCode = "G3245D",
                    LocationCity = "Glasgow",
                    AboutEvent = "Andre Ward did it all in his boxing career: Olympic Gold as an amateur and undefeated World Champion as a professional." +
                                 "Andre started boxing at the age of 9 and went on to win 115 of 120 amateur contests - culminating in an Olympic Gold in Athens in 2004." +
                                 "As a professional Andre won World Titles at both Super-Middleweight and Light-Heavyweight. He retired with an unbeaten 32-0 record in 2017 as one of the best pound-for-pound fighters on the planet." +
                                 "Event guests will gain insight into Andre's career - in which he was trained throughout by his godfather Virgil Hunter - and hear about what it takes to get to the top of the boxing world.",
                    Photo = "Glasgow",
                    TotalSeats = 88,
                    AmountGoing = 22,
                    RemainingSeats = 66

                },
                new Promotion {
                    // id - autogenerated 
                    Name ="Promotion 2",
                    PromotedBy = "King Boxing",
                    PromotionDate = new DateTime(2020, 7, 2),
                    PromotionStartTime = new TimeSpan(19, 30, 0),
                    PromotionEndTime = new TimeSpan(20, 30, 0),

                    LocationBuiding = "The Big Ole Pizaa Joint",
                    LocationStreetAddress = "22 Hap'nin street",
                    LocationPostCode = "G3245D",
                    LocationCity = "Glasgow",
                    AboutEvent = "Andre Ward did it all in his boxing career: Olympic Gold as an amateur and undefeated World Champion as a professional." +
                                 "Andre started boxing at the age of 9 and went on to win 115 of 120 amateur contests - culminating in an Olympic Gold in Athens in 2004." +
                                 "As a professional Andre won World Titles at both Super-Middleweight and Light-Heavyweight. He retired with an unbeaten 32-0 record in 2017 as one of the best pound-for-pound fighters on the planet." +
                                 "Event guests will gain insight into Andre's career - in which he was trained throughout by his godfather Virgil Hunter - and hear about what it takes to get to the top of the boxing world.",
                    Photo = "Glasgow",
                    TotalSeats = 88,
                    AmountGoing = 22,
                    RemainingSeats = 66
                },
                new Promotion {
                    // id - autogenerated 
                    Name ="Promotion 1",
                    PromotedBy = "King Boxing",
                    PromotionDate = new DateTime(2018, 4, 1),
                    PromotionStartTime = new TimeSpan(19, 30, 0),
                    PromotionEndTime = new TimeSpan(20, 30, 0),

                    LocationBuiding = "The Big Ole Pizaa Joint",
                    LocationStreetAddress = "22 Hap'nin street",
                    LocationPostCode = "G3245D",
                    LocationCity = "Glasgow",
                    AboutEvent = "Andre Ward did it all in his boxing career: Olympic Gold as an amateur and undefeated World Champion as a professional." +
                                 "Andre started boxing at the age of 9 and went on to win 115 of 120 amateur contests - culminating in an Olympic Gold in Athens in 2004." +
                                 "As a professional Andre won World Titles at both Super-Middleweight and Light-Heavyweight. He retired with an unbeaten 32-0 record in 2017 as one of the best pound-for-pound fighters on the planet." +
                                 "Event guests will gain insight into Andre's career - in which he was trained throughout by his godfather Virgil Hunter - and hear about what it takes to get to the top of the boxing world.",
                    Photo = "Glasgow",
                    TotalSeats = 88,
                    AmountGoing = 22,
                    RemainingSeats = 66

                },
                new Promotion {
                    // id - autogenerated 
                    Name ="Promotion 2",
                    PromotedBy = "King Boxing",
                    PromotionDate = new DateTime(2019, 7, 2),
                    PromotionStartTime = new TimeSpan(19, 30, 0),
                    PromotionEndTime = new TimeSpan(20, 30, 0),

                    LocationBuiding = "The Big Ole Pizaa Joint",
                    LocationStreetAddress = "22 Hap'nin street",
                    LocationPostCode = "G3245D",
                    LocationCity = "Glasgow",
                    AboutEvent = "Andre Ward did it all in his boxing career: Olympic Gold as an amateur and undefeated World Champion as a professional." +
                                 "Andre started boxing at the age of 9 and went on to win 115 of 120 amateur contests - culminating in an Olympic Gold in Athens in 2004." +
                                 "As a professional Andre won World Titles at both Super-Middleweight and Light-Heavyweight. He retired with an unbeaten 32-0 record in 2017 as one of the best pound-for-pound fighters on the planet." +
                                 "Event guests will gain insight into Andre's career - in which he was trained throughout by his godfather Virgil Hunter - and hear about what it takes to get to the top of the boxing world.",
                    Photo = "Glasgow",
                    TotalSeats = 88,
                    AmountGoing = 22,
                    RemainingSeats = 66
                },
                new Promotion {
                    // id - autogenerated 
                    Name ="Promotion 1",
                    PromotedBy = "King Boxing",
                    PromotionDate = new DateTime(2020, 4, 1),
                    PromotionStartTime = new TimeSpan(19, 30, 0),
                    PromotionEndTime = new TimeSpan(20, 30, 0),

                    LocationBuiding = "The Big Ole Pizaa Joint",
                    LocationStreetAddress = "22 Hap'nin street",
                    LocationPostCode = "G3245D",
                    LocationCity = "Glasgow",
                    AboutEvent = "Andre Ward did it all in his boxing career: Olympic Gold as an amateur and undefeated World Champion as a professional." +
                                 "Andre started boxing at the age of 9 and went on to win 115 of 120 amateur contests - culminating in an Olympic Gold in Athens in 2004." +
                                 "As a professional Andre won World Titles at both Super-Middleweight and Light-Heavyweight. He retired with an unbeaten 32-0 record in 2017 as one of the best pound-for-pound fighters on the planet." +
                                 "Event guests will gain insight into Andre's career - in which he was trained throughout by his godfather Virgil Hunter - and hear about what it takes to get to the top of the boxing world.",
                    Photo = "Glasgow",
                    TotalSeats = 88,
                    AmountGoing = 22,
                    RemainingSeats = 66
               
                },
                new Promotion {
                    // id - autogenerated 
                    Name ="Promotion 2",
                    PromotedBy = "King Boxing",
                    PromotionDate = new DateTime(2020, 7, 2),
                    PromotionStartTime = new TimeSpan(19, 30, 0),
                    PromotionEndTime = new TimeSpan(20, 30, 0),

                    LocationBuiding = "The Big Ole Pizaa Joint",
                    LocationStreetAddress = "22 Hap'nin street",
                    LocationPostCode = "G3245D",
                    LocationCity = "Glasgow",
                    AboutEvent = "Andre Ward did it all in his boxing career: Olympic Gold as an amateur and undefeated World Champion as a professional." +
                                 "Andre started boxing at the age of 9 and went on to win 115 of 120 amateur contests - culminating in an Olympic Gold in Athens in 2004." +
                                 "As a professional Andre won World Titles at both Super-Middleweight and Light-Heavyweight. He retired with an unbeaten 32-0 record in 2017 as one of the best pound-for-pound fighters on the planet." +
                                 "Event guests will gain insight into Andre's career - in which he was trained throughout by his godfather Virgil Hunter - and hear about what it takes to get to the top of the boxing world.",
                    Photo = "Glasgow",
                    TotalSeats = 88,
                    AmountGoing = 22,
                    RemainingSeats = 66
                },
                new Promotion {
                    /// id - autogenerated 
                    Name ="Promotion 1",
                    PromotedBy = "King Boxing",
                    PromotionDate = new DateTime(2020, 5, 20),
                    PromotionStartTime = new TimeSpan(19, 30, 0),
                    PromotionEndTime = new TimeSpan(20, 30, 0),

                    LocationBuiding = "The Big Ole Pizaa Joint",
                    LocationStreetAddress = "22 Hap'nin street",
                    LocationPostCode = "G3245D",
                    LocationCity = "Glasgow",
                    AboutEvent = "Andre Ward did it all in his boxing career: Olympic Gold as an amateur and undefeated World Champion as a professional." +
                                 "Andre started boxing at the age of 9 and went on to win 115 of 120 amateur contests - culminating in an Olympic Gold in Athens in 2004." +
                                 "As a professional Andre won World Titles at both Super-Middleweight and Light-Heavyweight. He retired with an unbeaten 32-0 record in 2017 as one of the best pound-for-pound fighters on the planet." +
                                 "Event guests will gain insight into Andre's career - in which he was trained throughout by his godfather Virgil Hunter - and hear about what it takes to get to the top of the boxing world.",
                    Photo = "Glasgow",
                    TotalSeats = 88,
                    AmountGoing = 22,
                    RemainingSeats = 66
                }
            };
            context.Promotions.AddRange(promotions);

           






            // ________________________________________________________________
            // Seeding Equipment and Suppliers

            // All Equipment will link to a Supplier. Suppliers defined here. 
            var suppliers = new List<Supplier>()
            {
                new Supplier {
                    // id - autogenerated 
                    Name ="Everlast",
                    Mobile = "07123123458",
                },
                 new Supplier {
                    // id - autogenerated 
                    Name ="Venum Elite",
                    Mobile = "07123123123",
                },
                  new Supplier {
                    // id - autogenerated 
                    Name ="Fairtex",
                    Mobile = "07123123234",
                },
                   new Supplier {
                    // id - autogenerated 
                    Name ="Trideer",
                    Mobile = "07123123345",
                }
            };

            context.Suppliers.AddRange(suppliers);




            var equipment = new List<Equipment>
            {
                new Equipment {
                    // id - autogenerated 
                    Name ="Boxing Ring",
                    Description ="Some top quality boxing gloves. Well maintained, ",
                    Price = 14.4F,
                    PurchaseDate = new DateTime(2016, 2, 19),
                    Quantity = 2,
                    SupplierID = suppliers[0].SupplierID,
                    Supplier = suppliers[0]
                },
                new Equipment {
                    // id - autogenerated 
                    Name ="Skipping Rope",
                    Description ="Some top quality boxing gloves. Well maintained, ",
                    Price = 14.4F,
                    PurchaseDate = new DateTime(2016, 2, 19),
                    Quantity = 12,
                    SupplierID = suppliers[0].SupplierID,
                    Supplier = suppliers[0]
                },
                new Equipment {
                    // id - autogenerated 
                    Name ="Boxing Gloves",
                    Description ="Some top quality boxing gloves. Well maintained, ",
                    Price = 14.4F,
                    PurchaseDate = new DateTime(2016, 2, 19),
                    Quantity = 26,
                    SupplierID = suppliers[0].SupplierID,
                    Supplier = suppliers[0]
                },
                new Equipment {
                    // id - autogenerated 
                    Name ="Speed Bags",
                    Description ="Some top quality boxing gloves. Well maintained, ",
                    Price = 14.4F,
                    PurchaseDate = new DateTime(2016, 2, 19),
                    Quantity = 4,
                    SupplierID = suppliers[0].SupplierID,
                    Supplier = suppliers[0]
                },


                new Equipment {
                    // id - autogenerated 
                    Name ="Double End Bag",
                    Description ="Some top quality boxing gloves. Well maintained, ",
                    Price = 14.4F,
                    PurchaseDate = new DateTime(2016, 2, 19),
                    Quantity =3,
                    SupplierID = suppliers[0].SupplierID,
                    Supplier = suppliers[0]
                },
                new Equipment {
                    Name ="Hanging Heavy Bag",
                    Description ="Some top quality boxing gloves. Well maintained, ",
                    Price = 14.4F,
                    PurchaseDate = new DateTime(2018, 2, 19),
                    Quantity = 8,
                    SupplierID = suppliers[1].SupplierID,
                    Supplier = suppliers[1]
                },
                new Equipment {
                    Name ="Angled Heavy Bag",
                    Description ="Some top quality boxing gloves. Well maintained, ",
                    Price = 14.4F,
                    PurchaseDate = new DateTime(2009, 2, 19),
                    Quantity = 11,
                    SupplierID = suppliers[3].SupplierID,
                    Supplier = suppliers[3]
                },
                new Equipment {
                    Name ="Teardrop Punching Bag",
                    Description ="Speed Bag: Some top quality boxing gloves. Well maintained, ",
                    Price = 14.4F,
                    PurchaseDate = new DateTime(2010, 2, 19),
                    Quantity = 8,
                    SupplierID = suppliers[3].SupplierID,
                    Supplier = suppliers[3]
                }
            };

            context.Equipment.AddRange(equipment);









            //_________________________________________________________________
            // Seeding an Admin user

            string userName = "admin@test.com";
            string password = "Password_1";
            //  var passwordHash = new PasswordHasher();
            //  password = passwordHash.HashPassword(password);

            var user = userManager.FindByName(userName);

            if (user == null)
            {
                var newUser = new Staff()
                {
                    Forename = "Robert",
                    Surname = "Lilt",
                    DOB = new DateTime(1964, 7, 9),
                    Title = "Mr",
                    PhoneNumber = "01418920828",
                    Mobile = "07418920828",
                    RepeatMobile = "07418920828",
                    UserName = userName,
                    Email = userName,
                    EmailConfirmed = true

                };
                
                userManager.Create(newUser, password);
                userManager.AddToRole(newUser.Id, RoleNames.ROLE_ADMINISTRATOR);
            }



            // Seeding a staff user 
            string userName1 = "staff@test.com";
            string password1 = "Password_1";
            //  var passwordHash = new PasswordHasher();
            //  password = passwordHash.HashPassword(password);

            var staff = userManager.FindByName(userName1);

            if (staff == null)
            {
                var newStaffUser = new Staff()
                {
                    Forename = "Billy",
                    Surname = "Murray",
                    DOB = new DateTime(1999, 2, 9),
                    Title = "Mrs",
                    PhoneNumber = "01418920829",
                    Mobile = "07418920829",
                    RepeatMobile = "07418920829",
                    UserName = userName1,
                    Email = userName1,
                    EmailConfirmed = true

                };

                userManager.Create(newStaffUser, password1);
                userManager.AddToRole(newStaffUser.Id, RoleNames.ROLE_STAFF);
            }


            // Seeding a staff user 2
            string userName2 = "staffWilliam@test.com";
            string password2 = "Password_1";
            //  var passwordHash = new PasswordHasher();
            //  password = passwordHash.HashPassword(password);

            var staff2 = userManager.FindByName(userName2);

            if (staff2 == null)
            {
                var newStaffUser2 = new Staff()
                {
                    Forename = "Sarah",
                    Surname = "Blob",
                    DOB = new DateTime(2002, 11, 10),
                    Title = "Mrs",
                    PhoneNumber = "01418920830",
                    Mobile = "074189208230",
                    RepeatMobile = "074189208230",
                    UserName = userName2,
                    Email = userName2,
                    EmailConfirmed = true

                };

                userManager.Create(newStaffUser2, password2);
                userManager.AddToRole(newStaffUser2.Id, RoleNames.ROLE_STAFF);
            }








            // Seed boxers/coaches
            var boxerUsers = new List<BoxerUser>
            {
                new BoxerUser {

                    Title ="Mr",
                    Email = "6@test.com",
                    Forename = "Robert",
                    Surname = "Pitch",
                    DOB = new DateTime(1964, 7, 9),
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    ImageSrc ="../../images/boxers/joshua-medway-sd-Pq5aDoO4-unsplash.jpg",
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = false,
                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "
                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "7@test.com",
                    ImageSrc ="../../images/boxers/colin-cassidy-akj4oRw8E04-unsplash.jpg",
                    Forename = "Johnny",
                    Surname = "Greenleaf",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,
                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "
                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "8@test.com",
                    ImageSrc ="../../images/boxers/steven-van-vLC--gwHnbQ-unsplash.jpg",
                    Forename = "Helen",
                    Surname = "Tacki",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "9@test.com",
                    ImageSrc ="../../images/boxers/emily-sea-coiWR0gT8Cw-unsplash.jpg",
                    Forename = "Garry",
                    Surname = "Gates",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "10@test.com",
                    ImageSrc ="../../images/boxers/filipe-almeida-mnEWC72eWDM-unsplash.jpg",
                    Forename = "Douglas",
                    Surname = "Butcher",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "11@test.com",
                    ImageSrc ="../../images/boxers/form-B6fw69UttOI-unsplash.jpg",
                    Forename = "James",
                    Surname = "Walker",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "12@test.com",
                    ImageSrc ="../../images/boxers/form-qQGAQMbURhU-unsplash.jpg",
                    Forename = "William",
                    Surname = "Wallace",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "13@test.com",
                    ImageSrc ="../../images/boxers/imani-clovis-tBt9JxuQBYs-unsplash.jpg",
                    Forename = "Elizabeth",
                    Surname = "Almond",
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "
                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "14@test.com",
                    ImageSrc ="../../images/boxers/jonathan-cosens-photography-jcp-v-YiCIbDjOQ-unsplash.jpg",
                    Forename = "Robert",
                    Surname = "Lilt",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "15@test.com",
                    ImageSrc ="../../images/boxers/form-B6fw69UttOI-unsplash.jpg",
                    Forename = "Violet",
                    Surname = "Malcolm",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },


                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "16@test.com",
                    ImageSrc ="../../images/boxers/joshua-medway-sd-Pq5aDoO4-unsplash.jpg",
                    Forename = "Robert",
                    Surname = "Pitch",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = false,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "17@test.com",
                    ImageSrc ="../../images/boxers/colin-cassidy-akj4oRw8E04-unsplash.jpg",
                    Forename = "John",
                    Surname = "Greenleaf",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "18@test.com",
                    ImageSrc ="../../images/boxers/steven-van-vLC--gwHnbQ-unsplash.jpg",
                    Forename = "Helen",
                    Surname = "Tacki",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,


                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "19@test.com",
                    ImageSrc ="../../images/boxers/emily-sea-coiWR0gT8Cw-unsplash.jpg",
                    Forename = "Garry",
                    Surname = "Gates",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "20@test.com",
                    ImageSrc ="../../images/boxers/filipe-almeida-mnEWC72eWDM-unsplash.jpg",
                    Forename = "Douglas",
                    Surname = "Butcher",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "21@test.com",
                    ImageSrc ="../../images/boxers/form-B6fw69UttOI-unsplash.jpg",
                    Forename = "James",
                    Surname = "Walker",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "22@test.com",
                    ImageSrc ="../../images/boxers/form-qQGAQMbURhU-unsplash.jpg",
                    Forename = "William",
                    Surname = "Wallace",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,


                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "23@test.com",
                    ImageSrc ="../../images/boxers/imani-clovis-tBt9JxuQBYs-unsplash.jpg",
                    Forename = "Elizabeth",
                    Surname = "Almond",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "24@test.com",
                    ImageSrc ="../../images/boxers/jonathan-cosens-photography-jcp-v-YiCIbDjOQ-unsplash.jpg",
                    Forename = "Robert",
                    Surname = "Lilt",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "25@test.com",
                    ImageSrc ="../../images/boxers/form-B6fw69UttOI-unsplash.jpg",
                    Forename = "Violet",
                    Surname = "Malcolm",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },



                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "26@test.com",
                    ImageSrc ="../../images/boxers/joshua-medway-sd-Pq5aDoO4-unsplash.jpg",
                    Forename = "Robert",
                    Surname = "Pitch",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = false,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "27@test.com",
                    ImageSrc ="../../images/boxers/colin-cassidy-akj4oRw8E04-unsplash.jpg",
                    Forename = "John",
                    Surname = "Greenleaf",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "28@test.com",
                    ImageSrc ="../../images/boxers/steven-van-vLC--gwHnbQ-unsplash.jpg",
                    Forename = "Helen",
                    Surname = "Tacki",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "29@test.com",
                    ImageSrc ="../../images/boxers/emily-sea-coiWR0gT8Cw-unsplash.jpg",
                    Forename = "Garry",
                    Surname = "Gates",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "30@test.com",
                    ImageSrc ="../../images/boxers/filipe-almeida-mnEWC72eWDM-unsplash.jpg",
                    Forename = "Douglas",
                    Surname = "Butcher",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "31@test.com",
                    ImageSrc ="../../images/boxers/form-B6fw69UttOI-unsplash.jpg",
                    Forename = "James",
                    Surname = "Walker",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "32@test.com",
                    ImageSrc ="../../images/boxers/form-qQGAQMbURhU-unsplash.jpg",
                    Forename = "William",
                    Surname = "Wallace",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "33@test.com",
                    ImageSrc ="../../images/boxers/imani-clovis-tBt9JxuQBYs-unsplash.jpg",
                    Forename = "Elizabeth",
                    Surname = "Almond",
                    DOB = new DateTime(1964, 7, 9),
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = false,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                },
                new BoxerUser {
                    Title ="Mr",
                    Mobile ="07490714777",
                    DetailsHidden = false,
                    Email = "34@test.com",
                    ImageSrc ="../../images/boxers/jonathan-cosens-photography-jcp-v-YiCIbDjOQ-unsplash.jpg",
                    Forename = "Robert",
                    Surname = "Lilt",
                    Instagram = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    LinkedIn = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Facebook = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Twitter = "https://www.youtube.com/watch?v=OJxCcCEobNs",
                    Available = true,

                    Description = "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. " +
                    "A lllong description of this boxer and any information that you deem relevant. "

                }

            };

            //foreach (var person in boxerUsers)
            //{
            //    string generalPassword = "Password_1";
            //    userManager.Create(person, generalPassword);
            //    userManager.AddToRole(person.Id, RoleNames.ROLE_BOXER);
            //}

            context.BoxerUsers.AddRange(boxerUsers);
            context.SaveChanges();




            // BoxingClass seeded data  
            var boxingClasses = new List<BoxingClass>()
            {
                new BoxingClass {
                    // id = 1 
                    Title ="Bag Blast",
                    Description = "Bag Blast is a blah du blah da."
                },
                new BoxingClass {
                                        
                    // id = 2
                    Title ="Open Training",
                    Description = "Open Training session is a lorium sertius derlerium. ",
                },
                new BoxingClass {
                    Title ="Kids' Classs (8 and Over)",
                    Description = "Session is s lorium sertius derlerium. ",
           
                },
                new BoxingClass {
                    Title ="All Levels Boxing",
                    Description = "Session is s lorium sertius derlerium. ",
            
                },
                new BoxingClass {
                    Title ="Pad Work Class",
                    Description = "Session is s lorium sertius derlerium. ",
                    
                },
                new BoxingClass {
                    Title ="Curcuits",
                    Description = "Curcuits is s lorium sertius derlerium. ",
              
                },
                new BoxingClass {
                    Title ="Kids' Classs (Under 8's)",
                    Description = "Sparring Session is s lorium sertius derlerium. ",
           
                },
                 new BoxingClass {
                    Title ="Kids' Classs (8 and Over)",
                    Description = "Sparring Session is s lorium sertius derlerium. ",
             
                },

            };

            context.BoxingClasses.AddRange(boxingClasses);




            var sceduledClasses = new List<Schedule>
            {
                // MONDAY
                new Schedule()
                {
                    Day = Day.MONDAY,
                    StartTime = new TimeSpan(10, 0, 0),
                    EndTime = new TimeSpan(11, 0, 0),
                    BoxingClass = boxingClasses[0],
                    BoxingClassID = boxingClasses[0].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },
                new Schedule()
                {
                    Day = Day.MONDAY,
                    StartTime = new TimeSpan(16, 0, 0),
                    EndTime = new TimeSpan(17, 30, 0),
                    BoxingClass = boxingClasses[1],
                    BoxingClassID = boxingClasses[1].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]

                },
                new Schedule()
                {
                    Day = Day.MONDAY,
                    StartTime = new TimeSpan(17, 0, 0),
                    EndTime = new TimeSpan(17, 45, 0),
                    BoxingClass = boxingClasses[2],
                    BoxingClassID = boxingClasses[2].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]

                },
                new Schedule()
                {
                    Day = Day.MONDAY,
                    StartTime = new TimeSpan(17, 45, 0),
                    EndTime = new TimeSpan(18, 30, 0),
                    BoxingClass = boxingClasses[3],
                    BoxingClassID = boxingClasses[3].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },
                new Schedule()
                {
                    Day = Day.MONDAY,
                    StartTime = new TimeSpan(18, 30, 0),
                    EndTime = new TimeSpan(19, 30, 0),
                    BoxingClass = boxingClasses[4],
                    BoxingClassID = boxingClasses[4].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]

                },
                new Schedule()
                {
                    Day = Day.MONDAY,
                    StartTime = new TimeSpan(19, 30, 0),
                    EndTime = new TimeSpan(20, 00, 0),
                    BoxingClass = boxingClasses[5],
                    BoxingClassID = boxingClasses[5].BoxingClassID,
                    ClassStatus = ClassStatus.FULLYBOOKED,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]

                },
                new Schedule()
                {
                    Day = Day.MONDAY,
                    StartTime = new TimeSpan(20, 0, 0),
                    EndTime = new TimeSpan(20, 30, 0),
                    BoxingClass = boxingClasses[6],
                    BoxingClassID = boxingClasses[6].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },
               




                /////////////
                // TUESDAY
                new Schedule()
                {
                    Day = Day.TUESDAY,
                    StartTime = new TimeSpan(16, 0, 0),
                    EndTime = new TimeSpan(17, 30, 0),
                    BoxingClass = boxingClasses[1],
                    BoxingClassID = boxingClasses[1].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]

                },
                new Schedule()
                {
                    Day = Day.TUESDAY,
                     StartTime = new TimeSpan(17, 30, 0),
                    EndTime = new TimeSpan(17, 45, 0),
                    BoxingClass = boxingClasses[0],
                    BoxingClassID = boxingClasses[0].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },
                new Schedule()
                {
                    Day = Day.TUESDAY,
                    StartTime = new TimeSpan(17, 45, 0),
                    EndTime = new TimeSpan(18, 30, 0),
                    BoxingClass = boxingClasses[4],
                    BoxingClassID = boxingClasses[4].BoxingClassID,
                    ClassStatus = ClassStatus.FULLYBOOKED,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]

                },
                new Schedule()
                {
                    Day = Day.TUESDAY,
                    StartTime = new TimeSpan(18, 30, 0),
                    EndTime = new TimeSpan(19, 30, 0),
                    BoxingClass = boxingClasses[5],
                    BoxingClassID = boxingClasses[5].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },
                new Schedule()
                {
                    Day = Day.TUESDAY,
                    StartTime = new TimeSpan(19, 30, 0),
                    EndTime = new TimeSpan(20, 0, 0),
                    BoxingClass = boxingClasses[6],
                    BoxingClassID = boxingClasses[6].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]

                },
                new Schedule()
                {
                    Day = Day.TUESDAY,
                    StartTime = new TimeSpan(20, 0, 0),
                    EndTime = new TimeSpan(20, 30, 0),
                    BoxingClass = boxingClasses[2],
                    BoxingClassID = boxingClasses[2].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]

                },
              





                ///////////////
                // WEDNESDAY
                new Schedule()
                {
                    Day = Day.WEDNESDAY,
                    StartTime = new TimeSpan(13, 0, 0),
                    EndTime = new TimeSpan(14, 30, 0),
                    BoxingClass = boxingClasses[2],
                    BoxingClassID = boxingClasses[2].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]


                },
                new Schedule()
                {
                    Day = Day.WEDNESDAY,
                    StartTime = new TimeSpan(16, 30, 0),
                    EndTime = new TimeSpan(17, 30, 0),
                    BoxingClass = boxingClasses[7],
                    BoxingClassID = boxingClasses[7].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]

                },
                new Schedule()
                {
                    Day = Day.WEDNESDAY,
                    StartTime = new TimeSpan(17, 30, 0),
                    EndTime = new TimeSpan(18, 30, 0),
                    BoxingClass = boxingClasses[0],
                    BoxingClassID = boxingClasses[0].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]

                },
                new Schedule()
                {
                    Day = Day.WEDNESDAY,
                    StartTime = new TimeSpan(18, 30, 0),
                    EndTime = new TimeSpan(19, 30, 0),
                    BoxingClass = boxingClasses[5],
                    BoxingClassID = boxingClasses[5].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]

                },
                new Schedule()
                {
                    Day = Day.WEDNESDAY,
                    StartTime = new TimeSpan(19, 30, 0),
                    EndTime = new TimeSpan(20, 45, 0),
                    BoxingClass = boxingClasses[6],
                    BoxingClassID = boxingClasses[6].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },






                /////////////
                // THURSDAY
                new Schedule()
                {
                    Day = Day.THURSDAY,
                    StartTime = new TimeSpan(16, 30, 0),
                    EndTime = new TimeSpan(17, 30, 0),
                    BoxingClass = boxingClasses[0],
                    BoxingClassID = boxingClasses[0].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },
                new Schedule()
                {
                    Day = Day.THURSDAY,
                    StartTime = new TimeSpan(17, 0, 0),
                    EndTime = new TimeSpan(18, 30, 0),
                    BoxingClass = boxingClasses[3],
                    BoxingClassID = boxingClasses[3].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },
                new Schedule()
                {
                    Day = Day.THURSDAY,
                    StartTime = new TimeSpan(19, 30, 0),
                    EndTime = new TimeSpan(20, 45, 0),
                    BoxingClass = boxingClasses[4],
                    BoxingClassID = boxingClasses[4].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },
                new Schedule()
                {
                    Day = Day.THURSDAY,
                    StartTime = new TimeSpan(20, 45, 0),
                    EndTime = new TimeSpan(21, 15, 0),
                    BoxingClass = boxingClasses[6],
                    BoxingClassID = boxingClasses[6].BoxingClassID,
                    ClassStatus = ClassStatus.CANCELLED,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },




                ///////////
                // FRIDAY
                new Schedule()
                {
                    Day = Day.FRIDAY,
                    StartTime = new TimeSpan(16, 30, 0),
                    EndTime= new TimeSpan(17, 30, 0),
                    BoxingClass = boxingClasses[1],
                    BoxingClassID = boxingClasses[1].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },
                new Schedule()
                {
                    Day = Day.FRIDAY,
                    StartTime = new TimeSpan(17, 30, 0),
                    EndTime = new TimeSpan(19, 0, 0),
                    BoxingClass = boxingClasses[2],
                    BoxingClassID = boxingClasses[2].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },
                new Schedule()
                {
                    Day = Day.FRIDAY,
                    StartTime = new TimeSpan(19, 0, 0),
                    EndTime = new TimeSpan(20, 45, 0),
                    BoxingClass = boxingClasses[4],
                    BoxingClassID = boxingClasses[4].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },
                new Schedule()
                {
                    Day = Day.FRIDAY,
                    StartTime = new TimeSpan(20, 45, 0),
                    EndTime = new TimeSpan(21, 0, 0),
                    BoxingClass = boxingClasses[7],
                    BoxingClassID = boxingClasses[7].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },



                // SATURDAY
                new Schedule()
                {
                    Day = Day.SATURDAY,
                    StartTime = new TimeSpan(07, 30, 0),
                    EndTime = new TimeSpan(08, 30, 0),
                    BoxingClass = boxingClasses[0],
                    BoxingClassID = boxingClasses[0].BoxingClassID,
                    ClassStatus = ClassStatus.CANCELLED,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]

                },
                new Schedule()
                {
                    Day = Day.SATURDAY,
                    StartTime = new TimeSpan(08, 30, 0),
                    EndTime = new TimeSpan(09, 30, 0),
                    BoxingClass = boxingClasses[7],
                    BoxingClassID = boxingClasses[7].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]
                },



                ////////////
                // SUNDAY
                new Schedule()
                {
                    Day = Day.SUNDAY,
                    StartTime = new TimeSpan(07, 0, 0),
                    EndTime = new TimeSpan(08, 30, 0),
                    BoxingClass = boxingClasses[2],
                    BoxingClassID = boxingClasses[2].BoxingClassID,
                    BoxerID = boxerUsers[4].ID,
                    Boxer = boxerUsers[4]


                }



            };


            context.Schedule.AddRange(sceduledClasses);

        }
    }
}



